[package]
name = "graphics"
version = "0.1.0"
edition = "2024"

[dependencies]
asset = { path = "../asset" }
ecs = { path = "../ecs" }
geometry = { path = "../geometry" }
gpu = { path = "../gpu" }
math = { path = "../math" }

exr = "1.73.0"
rand = "0.9.0"
